{
 "title": "Chain Forks",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "label": "Bucket", "query": "buckets()" }
  ]
 },
 "panels": [
  {
   "title": "Side Chains (Creators)",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"forks\" and r[\"_field\"] == \"index\" and r[\"_value\"] == 1)\n  |> group(columns: [\"signer\"])\n  |> count()\n  |> group()\n  |> sort(desc: true)\n  |> keep(columns: [\"signer\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Side Chain Blocks",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"forks\")\n  |> pivot(\n      rowKey:[\"_time\"],\n      columnKey: [\"_field\"],\n      valueColumn: \"_value\"\n  )\n  |> keep(columns: [\"_time\", \"group\", \"signer\", \"number\", \"parent_id\", \"id\", \"score\", \"length\", \"index\"])\n  |> drop(columns: [\"group\", \"_time\", \"index\"])\n  |> group()\n  |> sort(columns: [\"number\"], desc: true)"
    }
   ]
  },
  {
   "title": "Side Chains (Total Score)",
   "type": "timeseries",
   "description": "The constant green line shows the best chain total score. Points along that line show points at which the chain forked and total score was different.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"block_stats\" and r[\"_field\"] == \"total_score\")\n  |> drop(columns: [\"signer\"])"
    },
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"forks\")\n  |> filter(fn: (r) => r[\"_field\"] == \"score\")\n  |> group(columns: [\"group\"])\n  |> keep(columns: [\"_time\", \"group\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Side Chains (Depth)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"forks\")\n  |> filter(fn: (r) => r[\"_field\"] == \"index\")\n  |> group(columns: [\"group\"])\n  |> keep(columns: [\"_time\", \"group\", \"_value\"])"
    }
   ]
  }
 ]
}