{
 "title": "DPoS - Slots",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "label": "Bucket", "query": "buckets()" },
   {
    "name": "epoch_length",
    "label": "Epoch Length",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: \"${bucket}\",\n    tag: \"epoch_length\",\n    predicate: (r) => r._measurement == \"chain_config\"\n)"
   },
   {
    "name": "block_interval",
    "label": "Block Interval",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: \"${bucket}\",\n    tag: \"block_interval\",\n    predicate: (r) => r._measurement == \"chain_config\"\n)"
   },
   {
    "name": "seeder_interval",
    "label": "Seeder Interval",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: \"${bucket}\",\n    tag: \"seeder_interval\",\n    predicate: (r) => r._measurement == \"chain_config\"\n)"
   },
   {
    "name": "validator_eviction_threshold",
    "label": "Eviction Threshold",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: \"${bucket}\",\n    tag: \"validator_eviction_threshold\",\n    predicate: (r) => r._measurement == \"chain_config\"\n)"
   },
   {
    "name": "low_staking_period",
    "label": "Low Staking Period",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: \"${bucket}\",\n    tag: \"low_staking_period\",\n    predicate: (r) => r._measurement == \"chain_config\"\n)"
   },
   {
    "name": "medium_staking_period",
    "label": "Mid Staking Period",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: \"${bucket}\",\n    tag: \"medium_staking_period\",\n    predicate: (r) => r._measurement == \"chain_config\"\n)"
   },
   {
    "name": "high_staking_period",
    "label": "High Staking Period",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: \"${bucket}\",\n    tag: \"high_staking_period\",\n    predicate: (r) => r._measurement == \"chain_config\"\n)"
   },
   {
    "name": "cooldown_period",
    "label": "Cooldown Period",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: \"${bucket}\",\n    tag: \"cooldown_period\",\n    predicate: (r) => r._measurement == \"chain_config\"\n)"
   },
   {
    "name": "hayabusa_tp",
    "label": "Hayabusa TP",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: \"${bucket}\",\n    tag: \"hayabusa_tp\",\n    predicate: (r) => r._measurement == \"chain_config\"\n)"
   },
   {
    "name": "hayabusa_fork_block",
    "label": "Hayabusa Fork Block",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: \"${bucket}\",\n    tag: \"hayabusa_fork_block\",\n    predicate: (r) => r._measurement == \"chain_config\"\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "🔮🔮 Future Slots",
   "type": "table",
   "description": "Only blocks in the current epoch can be predicted. If we are viewing the last block in the current epoch, this list will be empty",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "latestRecord = from(bucket: \"${bucket}\")\n  |> range(start: 2015-01-01T00:00:00Z, stop: 2100-01-01T00:00:00Z)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dpos_future_slots\")\n  |> filter(fn: (r) => r[\"_field\"] == \"block_number\")\n  |> group()\n  |> last()\n  |> findRecord(fn: (key) => true, idx: 0)\n\nlatestTime = latestRecord._time\n\nfrom(bucket: \"${bucket}\")\n  |> range(start: latestTime)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dpos_future_slots\")\n  |> pivot(\n      rowKey:[\"_time\"],\n      columnKey: [\"_field\"],\n      valueColumn: \"_value\"\n  )\n  |> group()\n  |> keep(columns: [\"signer\", \"block_in_epoch\", \"block_number\"])\n  |> sort(columns: [\"block_number\"])"
    }
   ]
  },
  {
   "title": "🚨🚨 Missed Slots",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: -10y)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dpos_missed_slots\")\n  |> limit(n: 200)\n  |> pivot(\n      rowKey:[\"_time\"],\n      columnKey: [\"_field\"],\n      valueColumn: \"_value\"\n  )\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> keep(columns: [\"_time\", \"block_number\", \"signer\"])"
    }
   ]
  },
  {
   "title": "👑👑 Filled Slot Leader board",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"validator_overview\" and r[\"_field\"] == \"block_number\")\n  |> pivot(\n      rowKey:[\"_time\"],\n      columnKey: [\"_field\"],\n      valueColumn: \"_value\"\n  )\n  |> group(columns: [\"signer\"])\n  |> map(fn: (r) => ({r with _value: 1}))\n  |> count(column: \"_value\")\n  |> group()\n  |> sort(columns: [\"_value\"], desc: true)\n"
    }
   ]
  },
  {
   "title": "😈😈 Missed Slot Leader board",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: -10y)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dpos_missed_slots\")\n  |> pivot(\n      rowKey:[\"_time\"],\n      columnKey: [\"_field\"],\n      valueColumn: \"_value\"\n  )\n  |> group(columns: [\"signer\"])\n  |> map(fn: (r) => ({r with _value: 1}))\n  |> count(column: \"_value\")\n  |> group()\n  |> sort(columns: [\"_value\"], desc: true)\n"
    }
   ]
  },
  {
   "title": "Previously Filled",
   "type": "table",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 22 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"validator_overview\")\n  |> filter(fn: (r) => r[\"_field\"] == \"epoch\" or r[\"_field\"] == \"block_in_epoch\" or r[\"_field\"] == \"block_number\")\n  |> pivot(\n      rowKey:[\"_time\"],\n      columnKey: [\"_field\"],\n      valueColumn: \"_value\"\n  )\n  |> group()\n  |> sort(desc: true, columns: [\"_time\"])\n  |> keep(columns: [\"_time\", \"block_in_epoch\", \"block_number\", \"epoch\", \"signer\"])"
    }
   ]
  }
 ]
}