{
 "title": "DPoS",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "label": "Bucket", "query": "buckets()" }
  ]
 },
 "panels": [
  {
   "title": "Finality",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"validator_overview\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /(active_stake|online_stake|online_validators|active_validators|epoch)/)\n  |> map(fn: (r) => ({\n    r with \n    _value: float(v: r._value)\n  }))\n  |> group()\n  |> pivot(\n    rowKey: [\"_time\"],\n    columnKey: [\"_field\"],\n    valueColumn: \"_value\"\n  )\n  |> map(fn: (r) => ({\n    _time: r._time,\n    _value: 1.0,\n    epoch: int(v: r.epoch),\n    total_stake: r.active_stake,\n    voting_stake: r.online_stake,\n    finality_threshold: float(v: r.active_stake) * (2.0 / 3.0),\n    voting_percentage: string(v: float(v: r.online_stake) / float(v: r.active_stake) * 100.0) + \"%\",\n    signer_count: int(v: r.online_validators)\n  }))\n  |> group(columns: [\"epoch\"])\n  |> first()\n  |> group()\n  |> sort(columns: [\"epoch\"], desc: true)\n  |> drop(columns: [\"_time\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Staked VET",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hayabusa_validators\" and r[\"_field\"] != \"circulating_vet\")\n  |> drop(columns: [\"chain_tag\"])"
    }
   ]
  },
  {
   "title": "Block production probability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hayabusa_probability\")\n  |> drop(columns: [\"chain_tag\"])"
    }
   ]
  },
  {
   "title": "Auto renew stakers",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"queued_stakers\")\n  |> filter(fn: (r) => r[\"_field\"] == \"auto_renew\")\n  |> group(columns: [\"_value\"])\n  |> count(column: \"validator\")\n  |> map(fn: (r) => ({\n      _time: now(),\n      category: if r._value then \"Auto Renew Enabled\" else \"Auto Renew Disabled\",\n      count: r.validator\n    }))\n  |> drop(columns: [\"_value\", \"validator\"])"
    }
   ]
  },
  {
   "title": "Active Stakers Auto Renewal",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stakers_status\")\n  |> drop(columns: [\"chain_tag\", \"_measurement\", \"_start\", \"_stop\"])\n  |> last()\n  |> pivot(rowKey: [\"_time\", \"validator\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.status == 2)\n  |> drop(columns: [\"validator_staked\", \"status\"])\n  |> group(columns: [\"auto_renew\"])\n  |> count(column: \"validator\")\n  |> map(fn: (r) => ({\n      _time: now(),\n      category: if r.auto_renew then \"Auto Renew Enabled\" else \"Auto Renew Disabled\",\n      count: r.validator\n    }))\n  |> drop(columns: [\"auto_renew\"])"
    }
   ]
  },
  {
   "title": "Staked Vet %",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 10, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hayabusa_validators\")\n  |> filter(fn: (r) => r[\"_field\"] == \"circulating_vet\" or r[\"_field\"] == \"total_stake\")\n  |> last()\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n    _time: r._time,\n    _value: float(v: r.total_stake) / float(v: r.circulating_vet) * 100.0\n  }))"
    }
   ]
  },
  {
   "title": "PoS active",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 13, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"block_stats\" and r[\"_field\"] == \"pos_active\")\n  |> drop(columns: [\"chain_tag\", \"block_number\", \"signer\"])\n  |> last()"
    }
   ]
  },
  {
   "title": "Stakers on Cooldown",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stakers_status\")\n  |> filter(fn: (r) => r[\"_field\"] == \"status\")\n  |> last()\n  |> filter(fn: (r) => r[\"_value\"] == 3)\n  |> group(columns: [\"status\"])\n  |> count()\n"
    }
   ]
  },
  {
   "title": "Stakers Exited",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stakers_status\")\n  |> filter(fn: (r) => r[\"_field\"] == \"status\")\n  |> last()\n  |> filter(fn: (r) => r[\"_value\"] == 4)\n  |> group(columns: [\"status\"])\n  |> count()\n"
    }
   ]
  },
  {
   "title": "Stakers by period",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"queued_stakers\")\n  |> filter(fn: (r) => r[\"_field\"] == \"period\")\n  |> group(columns: [\"_value\"])\n  |> count(column: \"validator\")\n  |> map(fn: (r) => ({\n      _time: now(),\n      _value: r._value,  // Keep the original value for sorting\n      period_label: string(v: r._value) + \" days\",\n      count: r.validator\n    }))\n  |> sort(columns: [\"_value\"])\n  |> drop(columns: [\"_value\"])"
    }
   ]
  },
  {
   "title": "Active Stakers by period",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 32 },
   "targets": [
    {
     "query": "activeStakers = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"stakers_status\")\n  |> filter(fn: (r) => r._field == \"status\")\n  |> last()\n  |> filter(fn: (r) => r._value == 2)\n  |> pivot(rowKey:[\"_time\", \"validator\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  \nqueuedStakers = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"queued_stakers\")\n  |> filter(fn: (r) => r._field == \"period\")\n  |> pivot(rowKey:[\"_time\", \"validator\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n\njoin(\n  tables: {active: activeStakers, queued: queuedStakers},\n  on: [\"validator\"]\n)\n  |> group(columns: [\"period\"])\n  |> count(column: \"validator\")\n  |> map(fn: (r) => ({\n      _time: now(),\n      _measurement: \"stakers_by_period\",\n      _field: string(v: r.period) + \" days\",\n      _value: r.validator,\n    }))\n  |> sort(columns: [\"period\"])"
    }
   ]
  },
  {
   "title": "Online validators",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hayabusa_validators\" and (r[\"_field\"] == \"online_validators\" or r[\"_field\"] == \"offline_validators\"))\n  |> last()\n  |> drop(columns: [\"chain_tag\"])"
    }
   ]
  },
  {
   "title": "Active Stakers by stake",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "// Define bucket ranges\nbucketInterval = 115000000000000000\nminStake = 25000000000000000\ndivisor = 1000000000\nbucket1 = minStake + bucketInterval\nbucket2 = bucket1 + bucketInterval\nbucket3 = bucket2 + bucketInterval\nbucket4 = bucket3 + bucketInterval\n\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stakers_status\")\n  |> drop(columns: [\"chain_tag\", \"_measurement\", \"_start\", \"_stop\"])\n  |> last()\n  |> pivot(rowKey: [\"_time\", \"validator\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.status == 2)\n  |> drop(columns: [\"auto_renew\", \"status\"])\n  |> map(fn: (r) => ({\n      _time: now(),\n      _value: r.validator_staked,\n      bucket: \n        if float(v: r.validator_staked)/float(v: divisor) < bucket1 then \"1. 25 - 140 M\"\n        else if float(v: r.validator_staked)/float(v: divisor) < bucket2 then \"2. 140 - 255 M\"\n        else if float(v: r.validator_staked)/float(v: divisor) < bucket3 then \"3. 255 - 370 M\"\n        else if float(v: r.validator_staked)/float(v: divisor) < bucket4 then \"4. 370 - 485 M\" \n        else \"5. 485 - 600 M\"\n    }))\n  |> group(columns: [\"bucket\"])\n  |> count()"
    }
   ]
  },
  {
   "title": "Stakers by stake",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "// Define bucket ranges\nbucketInterval = 115000000000000000\nminStake = 25000000000000000\ndivisor = 1000000000\nbucket1 = minStake + bucketInterval\nbucket2 = bucket1 + bucketInterval\nbucket3 = bucket2 + bucketInterval\nbucket4 = bucket3 + bucketInterval\n\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"queued_stakers\")\n  |> filter(fn: (r) => r[\"_field\"] == \"validator_staked\")\n  |> map(fn: (r) => ({\n      _time: now(),\n      _value: r._value,\n      bucket: \n        if float(v: r._value)/float(v: divisor) < bucket1 then \"1. 25 - 140 M\"\n        else if float(v: r._value)/float(v: divisor) < bucket2 then \"2. 140 - 255 M\"\n        else if float(v: r._value)/float(v: divisor) < bucket3 then \"3. 255 - 370 M\"\n        else if float(v: r._value)/float(v: divisor) < bucket4 then \"4. 370 - 485 M\" \n        else \"5. 485 - 600 M\"\n    }))\n  |> group(columns: [\"bucket\"])\n  |> count()\n  |> rename(columns: {_value: \"\"})\n  |> yield(name: \"count\")"
    }
   ]
  },
  {
   "title": "Validator filled blocks",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"recent_slots\")\n  |> filter(fn: (r) => r[\"_field\"] == \"block_number\")\n  |> filter(fn: (r) => r[\"filled\"] == \"1\")\n  |> group(columns: [\"proposer\"])\n  |> count()\n  |> map(fn: (r) => ({\n    _name: r.proposer,\n    _value: r._value\n  }))"
    }
   ]
  },
  {
   "title": "Validator missed blocks",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "query": "// TODO: This never worked, `recent_slots` is for poa\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"recent_slots\")\n  |> filter(fn: (r) => r[\"_field\"] == \"block_number\")\n  |> filter(fn: (r) => r[\"filled\"] == \"0\")\n  |> group(columns: [\"proposer\"])\n  |> count()\n  |> map(fn: (r) => ({\n    _name: r.proposer,\n    _value: r._value\n  }))"
    }
   ]
  },
  {
   "title": "Next block validator",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hayabusa_validators\")\n  |> filter(fn: (r) => r[\"_field\"] == \"next_validator\")\n  |> last()\n  |> drop(columns: [\"chain_tag\"])"
    }
   ]
  }
 ]
}