{
 "title": "DPoS - Contract Events",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Contract Events",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"vechain\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"staker_events\")\n  |> drop(columns: [\"chain_tag\"])"
    }
   ]
  },
  {
   "title": "Contract Events",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"vechain\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"staker_events\")\n  |> drop(columns: [\"chain_tag\"])\n  |> group(columns: [\"_field\"], mode:\"by\")\n  |> sum(column: \"_value\")\n  |> group()\n  |> yield(name: \"_value\")\n  |> map(\n        fn: (r) => ({Event: r._field, Count: r._value}),\n    )\n  |> drop(columns: [\"_field\", \"_value\"])\n  |> group()\n  |> sort(desc: true, columns: [\"Event\"])"
    }
   ]
  },
  {
   "title": "ValidationQueued",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"vechain\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"staker_events\" and r[\"_field\"] == \"ValidationQueued\")\n  |> drop(columns: [\"chain_tag\"])"
    }
   ]
  },
  {
   "title": "DelegationAdded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"vechain\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"staker_events\" and r[\"_field\"] == \"DelegationAdded\")\n  |> drop(columns: [\"chain_tag\"])"
    }
   ]
  },
  {
   "title": "ValidatorSignaledExit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"vechain\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"staker_events\" and r[\"_field\"] == \"ValidationSignaledExit\")\n  |> drop(columns: [\"chain_tag\"])"
    }
   ]
  },
  {
   "title": "DelegationUpdatedAutoRenew",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"vechain\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"staker_events\" and r[\"_field\"] == \"DelegationSignaledExit\")\n  |> drop(columns: [\"chain_tag\"])"
    }
   ]
  },
  {
   "title": "ValidationWithdrawn",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "query": "from(bucket: \"vechain\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"staker_events\" and r[\"_field\"] == \"ValidationWithdrawn\")\n  |> drop(columns: [\"chain_tag\"])"
    }
   ]
  },
  {
   "title": "DelegationWithdrawn",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "query": "from(bucket: \"vechain\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"staker_events\" and r[\"_field\"] == \"DelegationWithdrawn\")\n  |> drop(columns: [\"chain_tag\"])"
    }
   ]
  }
 ]
}