{
 "title": "Single Authority View",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "proposer",
    "label": "Proposer",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(bucket: \"${bucket}\", tag: \"proposer\")"
    }
   },
   { "name": "bucket", "label": "Bucket", "query": "buckets()" }
  ]
 },
 "panels": [
  {
   "title": "Filled Slots",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"recent_slots\" and r[\"_field\"] == \"block_number\" and r.filled == \"1\" and r.proposer == \"${proposer}\")\n  |> limit(n: 1000)\n  |> map(fn: (r) => ({ slot: r._value, time: r._time}))\n  |> keep(columns: [\"slot\", \"time\"])\n  "
    }
   ]
  },
  {
   "title": "Missed Slots",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"recent_slots\")\n  |> filter(fn: (r) => r[\"_field\"] == \"block_number\")\n  |> filter(fn: (r) => r[\"proposer\"] == \"${proposer}\")\n  |> filter(fn: (r) => r[\"filled\"] == \"0\")\n  |> group()\n  |> count()\n  |> yield(name: \"_value\")"
    }
   ]
  },
  {
   "title": "Filled Slots",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"recent_slots\")\n  |> filter(fn: (r) => r[\"_field\"] == \"block_number\")\n  |> filter(fn: (r) => r[\"proposer\"] == \"${proposer}\")\n  |> filter(fn: (r) => r[\"filled\"] == \"1\")\n  |> group()\n  |> count()\n  |> yield(name: \"_value\")"
    }
   ]
  },
  {
   "title": "Missed Slots",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"recent_slots\" and r[\"_field\"] == \"block_number\" and r.filled == \"0\" and r.proposer == \"${proposer}\")\n  |> map(fn: (r) => ({ slot: r._value, time: r._time}))\n  |> keep(columns: [\"slot\", \"time\"])"
    }
   ]
  },
  {
   "title": "Missed/Filled slots %",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "a = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"recent_slots\")\n  |> filter(fn: (r) => r[\"_field\"] == \"block_number\")\n  |> filter(fn: (r) => r[\"proposer\"] == \"${proposer}\")\n  |> filter(fn: (r) => r[\"filled\"] == \"0\")\n  |> group()\n  |> count()\n      |> map(\n        fn: (r) => ({\n            _join: 0,\n            _value_a: r._value\n        }),\n    )\n\nb = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"recent_slots\")\n  |> filter(fn: (r) => r[\"_field\"] == \"block_number\")\n  |> filter(fn: (r) => r[\"proposer\"] == \"${proposer}\")\n  |> filter(fn: (r) => r[\"filled\"] == \"1\")\n  |> group()\n  |> count()\n      |> map(\n        fn: (r) => ({\n            _join: 0,\n            _value_b: r._value\n        }),\n    )\n\njoin(tables: {a: a, b: b}, on: [\"_join\"])\n  |> drop(columns: [\"_join\"])\n  |> map(\n        fn: (r) => ({\n            _value: float(v: r._value_a) / float(v: r._value_b) * 100.0\n        }),\n    )\n\n\n"
    }
   ]
  }
 ]
}