{
 "title": "DPoS VTHO dashboard",
 "tags": [ "thorflux-v0.0.16" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "label": "Bucket", "query": "buckets()" }
  ]
 },
 "panels": [
  {
   "title": "Finalized / Justified / Liveness",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"liveness\" and (r[\"_field\"] == \"finalized\" or r[\"_field\"] == \"justified_block\" or r[\"_field\"] == \"liveness\" or r[\"_field\"] == \"current_block\"))\n  |> drop(columns: [\"chain_tag\", \"block_number\", \"signer\"])"
    }
   ]
  },
  {
   "title": "VTHO - issued / burned (Finney)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hayabusa_gas\")\n  |> filter(fn: (r) => r[\"_field\"] == \"issued_burned_ratio\")\n  |> drop(columns: [\"chain_tag\"])"
    }
   ]
  },
  {
   "title": "Issued and burned VTHO (Finney)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hayabusa_gas\")\n  |> filter(fn: (r) => r[\"_field\"] == \"vtho_burned\" or r[\"_field\"] == \"vtho_issued\" or r[\"_field\"] == \"validators_share\" or r[\"_field\"] == \"delegators_share\")\n  |> drop(columns: [\"chain_tag\"])"
    }
   ]
  }
 ]
}