{
 "title": "Slots",
 "tags": [ "thorflux-v0.0.16" ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "label": "Bucket", "query": "buckets()" }
  ]
 },
 "panels": [
  {
   "title": "Total missed slots",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"recent_slots\" and r[\"_field\"] == \"block_number\")\n  |> filter(fn: (r) => r.filled == \"0\")\n  |> group()\n  |> count()\n  |> yield(name: \"_value\")"
    }
   ]
  },
  {
   "title": "Missed slots per day",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 4, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"recent_slots\" and r._field == \"block_number\")\r\n  |> filter(fn: (r) => r.filled == \"0\")\r\n  |> group(columns: [])\r\n  |> aggregateWindow(every: 1d, fn: count, createEmpty: true)\r\n  |> yield(name: \"count_per_day\")\r\n"
    }
   ]
  },
  {
   "title": "Worst Performing Nodes",
   "type": "table",
   "gridPos": { "h": 20, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"recent_slots\")\n  |> filter(fn: (r) => r[\"filled\"] == \"0\")\n  |> group(columns: [\"proposer\"])\n  |> count(column: \"_value\")\n  |> group()\n  |> sort(columns: [\"_value\"], desc: true)\n  |> map(fn: (r) => ({ r with count: r._value / 2})) \n  |> keep(columns: [\"count\", \"proposer\"])"
    }
   ]
  },
  {
   "title": "Total filled slots",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"recent_slots\" and r[\"_field\"] == \"block_number\")\n  |> filter(fn: (r) => r.filled == \"1\")\n  |> group()\n  |> count()\n  |> yield(name: \"_value\")"
    }
   ]
  },
  {
   "title": "Missed block numbers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 4, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"recent_slots\" and r._field == \"block_number\")\r\n  |> filter(fn: (r) => r.filled == \"0\")\r\n  |> yield(name: \"count_per_day\")\r\n"
    }
   ]
  },
  {
   "title": "Block process duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(thor_metrics_block_processed_duration_ms_sum{environment=~\"prd\", network=\"${bucket}\", module=~\"authority\"}[$__rate_interval]) / rate(thor_metrics_block_processed_duration_ms_count{environment=~\"prd\", network=\"${bucket}\", module=~\"authority\"}[$__rate_interval])",
     "legendFormat": "{{instance_name}} - {{instance_id}}"
    }
   ]
  }
 ]
}