package dashboards

import (
	"github.com/grafana/grafana-foundation-sdk/go/cog"
	"github.com/grafana/grafana-foundation-sdk/go/common"
	"github.com/grafana/grafana-foundation-sdk/go/dashboard"
	"github.com/grafana/grafana-foundation-sdk/go/stat"
	"github.com/grafana/grafana-foundation-sdk/go/table"
	"github.com/vechain/thorflux/dashgen"
)

// AuthorityOverviewDashboard implements Dashboard interface for the authority overview dashboard
type AuthorityOverviewDashboard struct {
	InfluxDBRef    dashboard.DataSourceRef
	DefaultGrafana dashboard.DataSourceRef
}

func (d AuthorityOverviewDashboard) Name() string {
	return "Authority Overview"
}

func (d AuthorityOverviewDashboard) OutputFilename() string {
	return "authority-overview.json"
}

func (d AuthorityOverviewDashboard) Generate() (*dashboard.Dashboard, error) {
	// Create the authority overview dashboard with bucket templating
	builder := dashboard.NewDashboardBuilder("Authority Overview Generated").
		Uid("authority-overview-generated").
		Tags([]string{"generated", "vechain", "thorflux", "authority"}).
		Description("Overview of VeChain Thor authority nodes performance and metrics - Generated by thorflux dashgen").
		Refresh("30s").
		Time("now-6h", "now").
		Timezone(common.TimeZoneBrowser).
		WithVariable(CreateBucketVariable(*d.InfluxDBRef.Uid)).
		WithPanel(
			// Header panel
			dashgen.StandardHeaderPanel("Authority Overview", d.DefaultGrafana),
		).
		WithPanel(
			// Number of signers stat panel
			d.numberOfSignersPanel(dashboard.GridPos{H: PanelHeight, W: HalfWidth, X: 0, Y: HeaderHeight}),
		).
		WithPanel(
			// Total missed slots stat panel
			d.totalMissedSlotsPanel(dashboard.GridPos{H: PanelHeight, W: HalfWidth, X: HalfWidth, Y: HeaderHeight}),
		).
		WithPanel(
			// Missed slots table panel
			d.missedSlotsTablePanel(dashboard.GridPos{H: PanelHeight, W: FullWidth, X: 0, Y: HeaderHeight + PanelHeight}),
		).
		WithPanel(
			// Worst performing authorities table panel
			d.worstPerformingPanel(dashboard.GridPos{H: PanelHeight, W: HalfWidth, X: 0, Y: HeaderHeight + 2*PanelHeight}),
		).
		WithPanel(
			// Most proposed blocks table panel
			d.mostProposedBlocksPanel(dashboard.GridPos{H: PanelHeight, W: HalfWidth, X: HalfWidth, Y: HeaderHeight + 2*PanelHeight}),
		)

	// Build the dashboard
	dashboardResource, err := builder.Build()
	if err != nil {
		return nil, err
	}

	return &dashboardResource, nil
}

func (d AuthorityOverviewDashboard) numberOfSignersPanel(pos dashboard.GridPos) cog.Builder[dashboard.Panel] {
	return stat.NewPanelBuilder().
		Title("# of Signers").
		GridPos(pos).
		Datasource(d.InfluxDBRef).
		Description("Total number of unique signers").
		ReduceOptions(common.NewReduceDataOptionsBuilder().
			Calcs([]string{"lastNotNull"}).
			Fields("/.*/")).
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket:"${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) =>
    r._measurement == "block_stats" 
  )
  |> keep(columns: ["signer"])
  |> group()
  |> distinct(column: "signer")
  |> count()`, d.InfluxDBRef),
		)
}

func (d AuthorityOverviewDashboard) missedSlotsTablePanel(pos dashboard.GridPos) cog.Builder[dashboard.Panel] {
	return table.NewPanelBuilder().
		Title("Missed Slots (Ignore 'block_number')").
		GridPos(pos).
		Datasource(d.InfluxDBRef).
		Description("Table showing missed slots with details").
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `import "strings"

from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "recent_slots" and r["_field"] == "block_number" and r["filled"] == "0")
  |> map(fn: (r) => ({ r with _value: 1 })) 
  |> drop(columns: ["chain_tag", "filled"])`, d.InfluxDBRef),
		)
}

func (d AuthorityOverviewDashboard) totalMissedSlotsPanel(pos dashboard.GridPos) cog.Builder[dashboard.Panel] {
	return stat.NewPanelBuilder().
		Title("Total Missed Slots").
		GridPos(pos).
		Datasource(d.InfluxDBRef).
		Description("Total count of missed validator slots").
		ReduceOptions(common.NewReduceDataOptionsBuilder().
			Calcs([]string{"lastNotNull"}).
			Fields("/.*/")).
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "recent_slots" and r["_field"] == "block_number")
  |> filter(fn: (r) => r.filled == "0")
  |> group()
  |> count()
  |> yield(name: "_value")`, d.InfluxDBRef),
		)
}

func (d AuthorityOverviewDashboard) worstPerformingPanel(pos dashboard.GridPos) cog.Builder[dashboard.Panel] {
	return table.NewPanelBuilder().
		Title("Worst Performing (Click Address to View Single Authority)").
		GridPos(pos).
		Datasource(d.InfluxDBRef).
		Description("Table of worst performing authorities by missed slots").
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "recent_slots")
  |> filter(fn: (r) => r["filled"] == "0")
  |> group(columns: ["proposer"])
  |> count(column: "_value")
  |> group()
  |> sort(columns: ["_value"], desc: true)
  |> map(fn: (r) => ({ r with count: r._value / 2})) 
  |> keep(columns: ["count", "proposer"])`, d.InfluxDBRef),
		)
}

func (d AuthorityOverviewDashboard) mostProposedBlocksPanel(pos dashboard.GridPos) cog.Builder[dashboard.Panel] {
	return table.NewPanelBuilder().
		Title("Most Proposed Blocks").
		GridPos(pos).
		Datasource(d.InfluxDBRef).
		Description("Table of authorities that proposed the most blocks").
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "recent_slots")
  |> filter(fn: (r) => r["filled"] == "1")
  |> group(columns: ["proposer"])
  |> count(column: "_value")
  |> group()
  |> sort(columns: ["_value"], desc: true)
  |> map(fn: (r) => ({ r with count: r._value / 2})) 
  |> keep(columns: ["count", "proposer"])`, d.InfluxDBRef),
		)
}
