package dashboards

import (
	"github.com/grafana/grafana-foundation-sdk/go/cog"
	"github.com/grafana/grafana-foundation-sdk/go/common"
	"github.com/grafana/grafana-foundation-sdk/go/dashboard"
	"github.com/grafana/grafana-foundation-sdk/go/table"
	"github.com/grafana/grafana-foundation-sdk/go/timeseries"
	"github.com/vechain/thorflux/dashgen"
)

// ChainForksDashboard implements Dashboard interface for the chain forks dashboard
type ChainForksDashboard struct {
	InfluxDBRef    dashboard.DataSourceRef
	DefaultGrafana dashboard.DataSourceRef
}

func (d ChainForksDashboard) Name() string {
	return "Chain Forks"
}

func (d ChainForksDashboard) OutputFilename() string {
	return "chain-forks.json"
}

func (d ChainForksDashboard) Generate() (*dashboard.Dashboard, error) {
	// Create the chain forks dashboard with bucket templating
	builder := dashboard.NewDashboardBuilder("Chain Forks Generated").
		Uid("chain-forks-generated").
		Tags([]string{"generated", "vechain", "thorflux", "forks"}).
		Description("Analysis of VeChain Thor blockchain forks and side chains - Generated by thorflux dashgen").
		Refresh("30s").
		Time("now-6h", "now").
		Timezone(common.TimeZoneBrowser).
		WithVariable(CreateBucketVariable(*d.InfluxDBRef.Uid)).
		WithPanel(
			// Header panel
			dashgen.StandardHeaderPanel("Chain Forks", d.DefaultGrafana),
		).
		WithPanel(
			// Side chains creators table panel
			d.sideChainsCreatorsPanel(dashboard.GridPos{H: PanelHeight, W: HalfWidth, X: 0, Y: HeaderHeight}),
		).
		WithPanel(
			// Side chain blocks table panel
			d.sideChainBlocksPanel(dashboard.GridPos{H: PanelHeight, W: HalfWidth, X: HalfWidth, Y: HeaderHeight}),
		).
		WithPanel(
			// Side chains total score timeseries panel
			d.sideChainsScorePanel(dashboard.GridPos{H: PanelHeight, W: HalfWidth, X: 0, Y: HeaderHeight + PanelHeight}),
		).
		WithPanel(
			// Side chains depth timeseries panel
			d.sideChainsDepthPanel(dashboard.GridPos{H: PanelHeight, W: HalfWidth, X: HalfWidth, Y: HeaderHeight + PanelHeight}),
		)

	// Build the dashboard
	dashboardResource, err := builder.Build()
	if err != nil {
		return nil, err
	}

	return &dashboardResource, nil
}

func (d ChainForksDashboard) sideChainsCreatorsPanel(pos dashboard.GridPos) cog.Builder[dashboard.Panel] {
	return table.NewPanelBuilder().
		Title("Side Chains (Creators)").
		GridPos(pos).
		Datasource(d.InfluxDBRef).
		Description("Table showing side chain creators and their activity").
		WithTarget(
			dashgen.NewInfluxDBQuery("B", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "forks" and r["_field"] == "index" and r["_value"] == 1)
  |> group(columns: ["signer"])
  |> count()
  |> group()
  |> sort(desc: true)
  |> keep(columns: ["signer", "_value"])`, d.InfluxDBRef),
		)
}

func (d ChainForksDashboard) sideChainBlocksPanel(pos dashboard.GridPos) cog.Builder[dashboard.Panel] {
	return table.NewPanelBuilder().
		Title("Side Chain Blocks").
		GridPos(pos).
		Datasource(d.InfluxDBRef).
		Description("Detailed table of side chain blocks and their properties").
		WithTarget(
			dashgen.NewInfluxDBQuery("B", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "forks")
  |> pivot(
      rowKey:["_time"],
      columnKey: ["_field"],
      valueColumn: "_value"
  )
  |> keep(columns: ["_time", "group", "signer", "number", "parent_id", "id", "score", "length", "index"])
  |> drop(columns: ["group", "_time", "index"])
  |> group()
  |> sort(columns: ["number"], desc: true)`, d.InfluxDBRef),
		)
}

func (d ChainForksDashboard) sideChainsScorePanel(pos dashboard.GridPos) cog.Builder[dashboard.Panel] {
	return timeseries.NewPanelBuilder().
		Title("Side Chains (Total Score)").
		GridPos(pos).
		Description("Time series showing total score comparison between main chain and side chains").
		Datasource(d.InfluxDBRef).
		Unit("short").
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "block_stats" and r["_field"] == "total_score")
  |> drop(columns: ["signer"])`, d.InfluxDBRef),
		).
		WithTarget(
			dashgen.NewInfluxDBQuery("B", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "forks")
  |> filter(fn: (r) => r["_field"] == "score")
  |> group(columns: ["group"])
  |> keep(columns: ["_time", "group", "_value"])`, d.InfluxDBRef),
		)
}

func (d ChainForksDashboard) sideChainsDepthPanel(pos dashboard.GridPos) cog.Builder[dashboard.Panel] {
	return timeseries.NewPanelBuilder().
		Title("Side Chains (Depth)").
		GridPos(pos).
		Description("Time series showing the depth/index of side chains over time").
		Datasource(d.InfluxDBRef).
		Unit("short").
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "forks")
  |> filter(fn: (r) => r["_field"] == "index")
  |> group(columns: ["group"])
  |> keep(columns: ["_time", "group", "_value"])`, d.InfluxDBRef),
		)
}
