package dashboards

import (
	"github.com/grafana/grafana-foundation-sdk/go/cog"
	"github.com/grafana/grafana-foundation-sdk/go/common"
	"github.com/grafana/grafana-foundation-sdk/go/dashboard"
	"github.com/grafana/grafana-foundation-sdk/go/stat"
	"github.com/grafana/grafana-foundation-sdk/go/table"
	"github.com/grafana/grafana-foundation-sdk/go/timeseries"
	"github.com/vechain/thorflux/dashgen"
)

// DposCurrentValidatorOverviewDashboard implements Dashboard interface for the DPoS current validator overview dashboard
type DposCurrentValidatorOverviewDashboard struct {
	InfluxDBRef    dashboard.DataSourceRef
	DefaultGrafana dashboard.DataSourceRef
}

func (d DposCurrentValidatorOverviewDashboard) Name() string {
	return "DPoS Current Validator Overview"
}

func (d DposCurrentValidatorOverviewDashboard) OutputFilename() string {
	return "dpos-current-validator-overview.json"
}

func (d DposCurrentValidatorOverviewDashboard) Generate() (*dashboard.Dashboard, error) {
	// Create the DPoS current validator overview dashboard with bucket templating
	builder := dashboard.NewDashboardBuilder("DPoS Current Validator Overview Generated").
		Uid("dpos-current-validator-gen").
		Tags([]string{"generated", "vechain", "thorflux", "dpos", "validators", "overview"}).
		Description("Comprehensive overview of all current DPoS validators and their performance - Generated by thorflux dashgen").
		Refresh("30s").
		Time("now-6h", "now").
		Timezone(common.TimeZoneBrowser).
		WithVariable(CreateBucketVariable(*d.InfluxDBRef.Uid)).
		WithPanel(
			// Header panel
			dashgen.StandardHeaderPanel("DPoS Current Validator Overview", d.DefaultGrafana),
		).
		WithPanel(
			// Active validators stat panel
			d.activeValidatorsPanel(),
		).
		WithPanel(
			// Total network stake stat panel
			d.totalNetworkStakePanel(),
		).
		WithPanel(
			// Average validator performance stat panel
			d.averagePerformancePanel(),
		).
		WithPanel(
			// Validator status overview panel
			d.validatorStatusOverviewPanel(),
		).
		WithPanel(
			// Top validators by stake table panel
			d.topValidatorsByStakePanel(),
		).
		WithPanel(
			// Validator performance comparison panel
			d.validatorPerformanceComparisonPanel(),
		).
		WithPanel(
			// Network health metrics panel
			d.networkHealthMetricsPanel(),
		).
		WithPanel(
			// Validator distribution panel
			d.validatorDistributionPanel(),
		).
		WithPanel(
			// Delegation activity panel
			d.delegationActivityPanel(),
		)

	// Build the dashboard
	dashboardResource, err := builder.Build()
	if err != nil {
		return nil, err
	}

	return &dashboardResource, nil
}

func (d DposCurrentValidatorOverviewDashboard) activeValidatorsPanel() cog.Builder[dashboard.Panel] {
	return stat.NewPanelBuilder().
		Title("Active Validators").
		Datasource(d.InfluxDBRef).
		Description("Total number of currently active validators").
		ReduceOptions(common.NewReduceDataOptionsBuilder().
			Calcs([]string{"lastNotNull"}).
			Fields("/.*/")).
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "validator_status" and r["_field"] == "is_active")
  |> filter(fn: (r) => r["_value"] == 1)
  |> group()
  |> count()
  |> yield(name: "_value")`, d.InfluxDBRef),
		)
}

func (d DposCurrentValidatorOverviewDashboard) totalNetworkStakePanel() cog.Builder[dashboard.Panel] {
	return stat.NewPanelBuilder().
		Title("Total Network Stake").
		Datasource(d.InfluxDBRef).
		Description("Total amount of VET staked across all validators").
		Unit("short").
		ReduceOptions(common.NewReduceDataOptionsBuilder().
			Calcs([]string{"lastNotNull"}).
			Fields("/.*/")).
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "network_stake" and r["_field"] == "total_staked")
  |> group()
  |> last()
  |> yield(name: "_value")`, d.InfluxDBRef),
		)
}

func (d DposCurrentValidatorOverviewDashboard) averagePerformancePanel() cog.Builder[dashboard.Panel] {
	return stat.NewPanelBuilder().
		Title("Average Performance").
		Datasource(d.InfluxDBRef).
		Description("Average performance across all active validators").
		Unit("percent").
		ReduceOptions(common.NewReduceDataOptionsBuilder().
			Calcs([]string{"lastNotNull"}).
			Fields("/.*/")).
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "validator_performance" and r["_field"] == "efficiency")
  |> group()
  |> mean()
  |> map(fn: (r) => ({ _value: r._value * 100.0 }))`, d.InfluxDBRef),
		)
}

func (d DposCurrentValidatorOverviewDashboard) validatorStatusOverviewPanel() cog.Builder[dashboard.Panel] {
	return timeseries.NewPanelBuilder().
		Title("Validator Status Overview").
		Description("Timeline showing validator status changes and network participation").
		Datasource(d.InfluxDBRef).
		Unit("short").
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "validator_status")
  |> group(columns: ["_field"])
  |> aggregateWindow(every: 5m, fn: count, createEmpty: false)`, d.InfluxDBRef),
		)
}

func (d DposCurrentValidatorOverviewDashboard) topValidatorsByStakePanel() cog.Builder[dashboard.Panel] {
	return table.NewPanelBuilder().
		Title("Top Validators by Stake").
		Datasource(d.InfluxDBRef).
		Description("Ranking of validators by total stake amount").
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "validator_stakes" and r["_field"] == "total_stake")
  |> group(columns: ["validator_address"])
  |> last()
  |> group()
  |> sort(columns: ["_value"], desc: true)
  |> limit(n: 25)`, d.InfluxDBRef),
		)
}

func (d DposCurrentValidatorOverviewDashboard) validatorPerformanceComparisonPanel() cog.Builder[dashboard.Panel] {
	return timeseries.NewPanelBuilder().
		Title("Validator Performance Comparison").
		Description("Performance comparison across different validators over time").
		Datasource(d.InfluxDBRef).
		Unit("percent").
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "validator_performance" and r["_field"] == "efficiency")
  |> group(columns: ["validator_address"])
  |> aggregateWindow(every: 10m, fn: mean, createEmpty: false)
  |> map(fn: (r) => ({ r with _value: r._value * 100.0 }))`, d.InfluxDBRef),
		)
}

func (d DposCurrentValidatorOverviewDashboard) networkHealthMetricsPanel() cog.Builder[dashboard.Panel] {
	return timeseries.NewPanelBuilder().
		Title("Network Health Metrics").
		Description("Overall network health indicators and consensus metrics").
		Datasource(d.InfluxDBRef).
		Unit("percent").
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "network_health")
  |> group(columns: ["_field"])
  |> aggregateWindow(every: 2m, fn: mean, createEmpty: false)
  |> map(fn: (r) => ({ r with _value: r._value * 100.0 }))`, d.InfluxDBRef),
		)
}

func (d DposCurrentValidatorOverviewDashboard) validatorDistributionPanel() cog.Builder[dashboard.Panel] {
	return stat.NewPanelBuilder().
		Title("Validator Distribution").
		Datasource(d.InfluxDBRef).
		Description("Distribution statistics of validators across different categories").
		ReduceOptions(common.NewReduceDataOptionsBuilder().
			Calcs([]string{"lastNotNull"}).
			Fields("/.*/")).
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "validator_categories")
  |> group(columns: ["category"])
  |> count()
  |> group()
  |> sum()`, d.InfluxDBRef),
		)
}

func (d DposCurrentValidatorOverviewDashboard) delegationActivityPanel() cog.Builder[dashboard.Panel] {
	return timeseries.NewPanelBuilder().
		Title("Delegation Activity").
		Description("Network-wide delegation activity and staking changes").
		Datasource(d.InfluxDBRef).
		Unit("short").
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "delegation_events")
  |> group(columns: ["event_type"])
  |> aggregateWindow(every: 15m, fn: count, createEmpty: false)`, d.InfluxDBRef),
		)
}
