package dashboards

import (
	"github.com/grafana/grafana-foundation-sdk/go/cog"
	"github.com/grafana/grafana-foundation-sdk/go/common"
	"github.com/grafana/grafana-foundation-sdk/go/dashboard"
	"github.com/grafana/grafana-foundation-sdk/go/stat"
	"github.com/grafana/grafana-foundation-sdk/go/table"
	"github.com/grafana/grafana-foundation-sdk/go/timeseries"
	"github.com/vechain/thorflux/dashgen"
)

// DposHistoricalStakerOverviewDashboard implements Dashboard interface for the DPoS historical staker overview dashboard
type DposHistoricalStakerOverviewDashboard struct {
	InfluxDBRef    dashboard.DataSourceRef
	DefaultGrafana dashboard.DataSourceRef
}

func (d DposHistoricalStakerOverviewDashboard) Name() string {
	return "DPoS Historical Staker Overview"
}

func (d DposHistoricalStakerOverviewDashboard) OutputFilename() string {
	return "dpos-historical-staker-overview.json"
}

func (d DposHistoricalStakerOverviewDashboard) Generate() (*dashboard.Dashboard, error) {
	// Create the DPoS historical staker overview dashboard with bucket templating
	builder := dashboard.NewDashboardBuilder("DPoS Historical Staker Overview Generated").
		Uid("dpos-historical-staker-gen").
		Tags([]string{"generated", "vechain", "thorflux", "dpos", "staking", "historical"}).
		Description("Historical overview of DPoS staking activities and staker statistics - Generated by thorflux dashgen").
		Refresh("5m").
		Time("now-7d", "now").
		Timezone(common.TimeZoneBrowser).
		WithVariable(CreateBucketVariable(*d.InfluxDBRef.Uid)).
		WithPanel(
			// Header panel
			dashgen.StandardHeaderPanel("DPoS Historical Staker Overview", d.DefaultGrafana),
		).
		WithPanel(
			// Total staked amount stat panel
			d.totalStakedAmountPanel(),
		).
		WithPanel(
			// Active stakers stat panel
			d.activeStakersPanel(),
		).
		WithPanel(
			// Staking timeline panel
			d.stakingTimelinePanel(),
		).
		WithPanel(
			// Top stakers table panel
			d.topStakersPanel(),
		).
		WithPanel(
			// Staking rewards panel
			d.stakingRewardsPanel(),
		).
		WithPanel(
			// Delegation changes panel
			d.delegationChangesPanel(),
		)

	// Build the dashboard
	dashboardResource, err := builder.Build()
	if err != nil {
		return nil, err
	}

	return &dashboardResource, nil
}

func (d DposHistoricalStakerOverviewDashboard) totalStakedAmountPanel() cog.Builder[dashboard.Panel] {
	return stat.NewPanelBuilder().
		Title("Total Staked Amount").
		Datasource(d.InfluxDBRef).
		Description("Total amount of VET currently staked in the system").
		Unit("short").
		ReduceOptions(common.NewReduceDataOptionsBuilder().
			Calcs([]string{"lastNotNull"}).
			Fields("/.*/")).
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "staking_stats" and r["_field"] == "total_staked")
  |> group()
  |> last()
  |> yield(name: "_value")`, d.InfluxDBRef),
		)
}

func (d DposHistoricalStakerOverviewDashboard) activeStakersPanel() cog.Builder[dashboard.Panel] {
	return stat.NewPanelBuilder().
		Title("Active Stakers").
		Datasource(d.InfluxDBRef).
		Description("Number of currently active stakers").
		ReduceOptions(common.NewReduceDataOptionsBuilder().
			Calcs([]string{"lastNotNull"}).
			Fields("/.*/")).
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "staking_stats" and r["_field"] == "active_stakers")
  |> group()
  |> last()
  |> yield(name: "_value")`, d.InfluxDBRef),
		)
}

func (d DposHistoricalStakerOverviewDashboard) stakingTimelinePanel() cog.Builder[dashboard.Panel] {
	return timeseries.NewPanelBuilder().
		Title("Staking Activity Timeline").
		Description("Timeline showing staking and unstaking activities over time").
		Datasource(d.InfluxDBRef).
		Unit("short").
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "staking_events")
  |> group(columns: ["event_type"])
  |> aggregateWindow(every: 1h, fn: count, createEmpty: false)`, d.InfluxDBRef),
		)
}

func (d DposHistoricalStakerOverviewDashboard) topStakersPanel() cog.Builder[dashboard.Panel] {
	return table.NewPanelBuilder().
		Title("Top Stakers").
		Datasource(d.InfluxDBRef).
		Description("Table showing the largest stakers in the system").
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "staker_balances")
  |> group(columns: ["staker_address"])
  |> last()
  |> group()
  |> sort(columns: ["_value"], desc: true)
  |> limit(n: 20)`, d.InfluxDBRef),
		)
}

func (d DposHistoricalStakerOverviewDashboard) stakingRewardsPanel() cog.Builder[dashboard.Panel] {
	return timeseries.NewPanelBuilder().
		Title("Staking Rewards Distribution").
		Description("Timeline showing staking rewards distribution over time").
		Datasource(d.InfluxDBRef).
		Unit("short").
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "staking_rewards")
  |> group(columns: ["reward_type"])
  |> aggregateWindow(every: 1h, fn: sum, createEmpty: false)`, d.InfluxDBRef),
		)
}

func (d DposHistoricalStakerOverviewDashboard) delegationChangesPanel() cog.Builder[dashboard.Panel] {
	return timeseries.NewPanelBuilder().
		Title("Delegation Changes").
		Description("Changes in delegation patterns over time").
		Datasource(d.InfluxDBRef).
		Unit("short").
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "delegation_events")
  |> group(columns: ["action"])
  |> aggregateWindow(every: 2h, fn: count, createEmpty: false)`, d.InfluxDBRef),
		)
}
