package dashboards

import (
	"github.com/grafana/grafana-foundation-sdk/go/cog"
	"github.com/grafana/grafana-foundation-sdk/go/common"
	"github.com/grafana/grafana-foundation-sdk/go/dashboard"
	"github.com/grafana/grafana-foundation-sdk/go/stat"
	"github.com/grafana/grafana-foundation-sdk/go/table"
	"github.com/grafana/grafana-foundation-sdk/go/timeseries"
	"github.com/vechain/thorflux/dashgen"
)

// DposSingleValidatorDashboard implements Dashboard interface for the DPoS single validator dashboard
type DposSingleValidatorDashboard struct {
	InfluxDBRef    dashboard.DataSourceRef
	DefaultGrafana dashboard.DataSourceRef
}

func (d DposSingleValidatorDashboard) Name() string {
	return "DPoS Single Validator"
}

func (d DposSingleValidatorDashboard) OutputFilename() string {
	return "dpos-single-validator.json"
}

func (d DposSingleValidatorDashboard) Generate() (*dashboard.Dashboard, error) {
	// Create the DPoS single validator dashboard with templating
	builder := dashboard.NewDashboardBuilder("DPoS Single Validator Generated").
		Uid("dpos-single-validator-generated").
		Tags([]string{"generated", "vechain", "thorflux", "dpos", "validator", "single"}).
		Description("Detailed view of a single DPoS validator performance and statistics - Generated by thorflux dashgen").
		Refresh("30s").
		Time("now-24h", "now").
		Timezone(common.TimeZoneBrowser).
		WithVariable(CreateBucketVariable(*d.InfluxDBRef.Uid)).
		WithVariable(d.createValidatorVariable()).
		WithPanel(
			// Header panel
			dashgen.StandardHeaderPanel("DPoS Single Validator", d.DefaultGrafana),
		).
		WithPanel(
			// Validator status stat panel
			d.validatorStatusPanel(),
		).
		WithPanel(
			// Total stake stat panel
			d.totalStakePanel(),
		).
		WithPanel(
			// Delegation count stat panel
			d.delegationCountPanel(),
		).
		WithPanel(
			// Performance timeline panel
			d.performanceTimelinePanel(),
		).
		WithPanel(
			// Block production panel
			d.blockProductionPanel(),
		).
		WithPanel(
			// Rewards distribution panel
			d.rewardsDistributionPanel(),
		).
		WithPanel(
			// Delegators table panel
			d.delegatorsTablePanel(),
		)

	// Build the dashboard
	dashboardResource, err := builder.Build()
	if err != nil {
		return nil, err
	}

	return &dashboardResource, nil
}

func (d DposSingleValidatorDashboard) createValidatorVariable() *dashboard.QueryVariableBuilder {
	// Create StringOrMap for validator query
	query := dashboard.StringOrMap{
		String: cog.ToPtr(`import "influxdata/influxdb/schema"

schema.tagValues(bucket: "${bucket}", tag: "validator_address")`),
	}

	// Create VariableOption for current value
	current := dashboard.VariableOption{
		Selected: cog.ToPtr(false),
		Text: dashboard.StringOrArrayOfString{
			String: cog.ToPtr(""),
		},
		Value: dashboard.StringOrArrayOfString{
			String: cog.ToPtr(""),
		},
	}

	return dashboard.NewQueryVariableBuilder("validator").
		Datasource(dashboard.DataSourceRef{
			Type: cog.ToPtr("influxdb"),
			Uid:  cog.ToPtr(*d.InfluxDBRef.Uid),
		}).
		Query(query).
		Label("Validator").
		Current(current).
		Hide(dashboard.VariableHideDontHide).
		Multi(false).
		Refresh(dashboard.VariableRefreshOnTimeRangeChanged)
}

func (d DposSingleValidatorDashboard) validatorStatusPanel() cog.Builder[dashboard.Panel] {
	return stat.NewPanelBuilder().
		Title("Validator Status").
		Datasource(d.InfluxDBRef).
		Description("Current status of the selected validator").
		ReduceOptions(common.NewReduceDataOptionsBuilder().
			Calcs([]string{"lastNotNull"}).
			Fields("/.*/")).
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "validator_status")
  |> filter(fn: (r) => r["validator_address"] == "${validator}")
  |> filter(fn: (r) => r["_field"] == "is_active")
  |> group()
  |> last()
  |> yield(name: "_value")`, d.InfluxDBRef),
		)
}

func (d DposSingleValidatorDashboard) totalStakePanel() cog.Builder[dashboard.Panel] {
	return stat.NewPanelBuilder().
		Title("Total Stake").
		Datasource(d.InfluxDBRef).
		Description("Total amount of VET staked to this validator").
		Unit("short").
		ReduceOptions(common.NewReduceDataOptionsBuilder().
			Calcs([]string{"lastNotNull"}).
			Fields("/.*/")).
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "validator_stakes")
  |> filter(fn: (r) => r["validator_address"] == "${validator}")
  |> filter(fn: (r) => r["_field"] == "total_stake")
  |> group()
  |> last()
  |> yield(name: "_value")`, d.InfluxDBRef),
		)
}

func (d DposSingleValidatorDashboard) delegationCountPanel() cog.Builder[dashboard.Panel] {
	return stat.NewPanelBuilder().
		Title("Active Delegators").
		Datasource(d.InfluxDBRef).
		Description("Number of active delegators for this validator").
		ReduceOptions(common.NewReduceDataOptionsBuilder().
			Calcs([]string{"lastNotNull"}).
			Fields("/.*/")).
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "validator_delegations")
  |> filter(fn: (r) => r["validator_address"] == "${validator}")
  |> group(columns: ["delegator_address"])
  |> count()
  |> group()
  |> sum()`, d.InfluxDBRef),
		)
}

func (d DposSingleValidatorDashboard) performanceTimelinePanel() cog.Builder[dashboard.Panel] {
	return timeseries.NewPanelBuilder().
		Title("Validator Performance").
		Description("Performance metrics timeline for the selected validator").
		Datasource(d.InfluxDBRef).
		Unit("percent").
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "validator_performance")
  |> filter(fn: (r) => r["validator_address"] == "${validator}")
  |> group(columns: ["_field"])
  |> aggregateWindow(every: 10m, fn: mean, createEmpty: false)`, d.InfluxDBRef),
		)
}

func (d DposSingleValidatorDashboard) blockProductionPanel() cog.Builder[dashboard.Panel] {
	return timeseries.NewPanelBuilder().
		Title("Block Production").
		Description("Block production activity for the selected validator").
		Datasource(d.InfluxDBRef).
		Unit("short").
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "recent_slots")
  |> filter(fn: (r) => r["proposer"] == "${validator}")
  |> group(columns: ["filled"])
  |> aggregateWindow(every: 30m, fn: count, createEmpty: false)`, d.InfluxDBRef),
		)
}

func (d DposSingleValidatorDashboard) rewardsDistributionPanel() cog.Builder[dashboard.Panel] {
	return timeseries.NewPanelBuilder().
		Title("Rewards Distribution").
		Description("Rewards earned and distributed by this validator").
		Datasource(d.InfluxDBRef).
		Unit("short").
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "validator_rewards")
  |> filter(fn: (r) => r["validator_address"] == "${validator}")
  |> group(columns: ["reward_type"])
  |> aggregateWindow(every: 1h, fn: sum, createEmpty: false)`, d.InfluxDBRef),
		)
}

func (d DposSingleValidatorDashboard) delegatorsTablePanel() cog.Builder[dashboard.Panel] {
	return table.NewPanelBuilder().
		Title("Top Delegators").
		Datasource(d.InfluxDBRef).
		Description("Table showing the top delegators for this validator").
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "validator_delegations")
  |> filter(fn: (r) => r["validator_address"] == "${validator}")
  |> group(columns: ["delegator_address"])
  |> last()
  |> group()
  |> sort(columns: ["_value"], desc: true)
  |> limit(n: 20)`, d.InfluxDBRef),
		)
}
