package dashboards

import (
	"github.com/grafana/grafana-foundation-sdk/go/cog"
	"github.com/grafana/grafana-foundation-sdk/go/common"
	"github.com/grafana/grafana-foundation-sdk/go/dashboard"
	"github.com/grafana/grafana-foundation-sdk/go/stat"
	"github.com/grafana/grafana-foundation-sdk/go/table"
	"github.com/grafana/grafana-foundation-sdk/go/timeseries"
	"github.com/vechain/thorflux/dashgen"
)

// DposSlotsDashboard implements Dashboard interface for the DPoS slots dashboard
type DposSlotsDashboard struct {
	InfluxDBRef    dashboard.DataSourceRef
	DefaultGrafana dashboard.DataSourceRef
}

func (d DposSlotsDashboard) Name() string {
	return "DPoS Slots"
}

func (d DposSlotsDashboard) OutputFilename() string {
	return "dpos-slots.json"
}

func (d DposSlotsDashboard) Generate() (*dashboard.Dashboard, error) {
	// Create the DPoS slots dashboard with bucket templating
	builder := dashboard.NewDashboardBuilder("DPoS Slots Generated").
		Uid("dpos-slots-generated").
		Tags([]string{"generated", "vechain", "thorflux", "dpos", "slots"}).
		Description("DPoS validator slots and block production analysis - Generated by thorflux dashgen").
		Refresh("30s").
		Time("now-6h", "now").
		Timezone(common.TimeZoneBrowser).
		WithVariable(CreateBucketVariable(*d.InfluxDBRef.Uid)).
		WithPanel(
			// Header panel
			dashgen.StandardHeaderPanel("DPoS Slots", d.DefaultGrafana),
		).
		WithPanel(
			// Current slot stat panel
			d.currentSlotPanel(dashboard.GridPos{H: PanelHeight, W: HalfWidth, X: 0, Y: HeaderHeight}),
		).
		WithPanel(
			// Block production rate panel
			d.blockProductionRatePanel(dashboard.GridPos{H: PanelHeight, W: HalfWidth, X: HalfWidth, Y: HeaderHeight}),
		).
		WithPanel(
			// Slots timeline panel
			d.slotsTimelinePanel(dashboard.GridPos{H: PanelHeight, W: HalfWidth, X: 0, Y: HeaderHeight + PanelHeight}),
		).
		WithPanel(
			// Missed slots table panel
			d.missedSlotsTablePanel(dashboard.GridPos{H: PanelHeight, W: HalfWidth, X: HalfWidth, Y: HeaderHeight + PanelHeight}),
		)

	// Build the dashboard
	dashboardResource, err := builder.Build()
	if err != nil {
		return nil, err
	}

	return &dashboardResource, nil
}

func (d DposSlotsDashboard) currentSlotPanel(pos dashboard.GridPos) cog.Builder[dashboard.Panel] {
	return stat.NewPanelBuilder().
		Title("Current Slot").
		GridPos(pos).
		Datasource(d.InfluxDBRef).
		Description("Current validator slot number").
		ReduceOptions(common.NewReduceDataOptionsBuilder().
			Calcs([]string{"lastNotNull"}).
			Fields("/.*/")).
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "recent_slots" and r["_field"] == "block_number")
  |> group()
  |> last()
  |> yield(name: "_value")`, d.InfluxDBRef),
		)
}

func (d DposSlotsDashboard) slotsTimelinePanel(pos dashboard.GridPos) cog.Builder[dashboard.Panel] {
	return timeseries.NewPanelBuilder().
		Title("Slots Timeline").
		GridPos(pos).
		Description("Timeline showing slot progression and validator assignments").
		Datasource(d.InfluxDBRef).
		Unit("short").
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "recent_slots")
  |> filter(fn: (r) => r["_field"] == "block_number")
  |> group(columns: ["proposer", "filled"])
  |> keep(columns: ["_time", "_value", "proposer", "filled"])`, d.InfluxDBRef),
		)
}

func (d DposSlotsDashboard) missedSlotsTablePanel(pos dashboard.GridPos) cog.Builder[dashboard.Panel] {
	return table.NewPanelBuilder().
		Title("Missed Slots Details").
		GridPos(pos).
		Datasource(d.InfluxDBRef).
		Description("Detailed table of missed slots by validator").
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "recent_slots" and r["_field"] == "block_number" and r["filled"] == "0")
  |> keep(columns: ["_time", "_value", "proposer", "filled"])
  |> sort(columns: ["_time"], desc: true)`, d.InfluxDBRef),
		)
}

func (d DposSlotsDashboard) blockProductionRatePanel(pos dashboard.GridPos) cog.Builder[dashboard.Panel] {
	return timeseries.NewPanelBuilder().
		Title("Block Production Rate").
		GridPos(pos).
		Description("Rate of block production over time").
		Datasource(d.InfluxDBRef).
		Unit("percent").
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "recent_slots" and r["_field"] == "block_number")
  |> aggregateWindow(every: 5m, fn: count, createEmpty: false)
  |> map(fn: (r) => ({ _value: float(v: r._value) / 300.0 * 100.0, _time: r._time }))`, d.InfluxDBRef),
		)
}
