package dashboards

import (
	"github.com/grafana/grafana-foundation-sdk/go/cog"
	"github.com/grafana/grafana-foundation-sdk/go/common"
	"github.com/grafana/grafana-foundation-sdk/go/dashboard"
	"github.com/grafana/grafana-foundation-sdk/go/stat"
	"github.com/grafana/grafana-foundation-sdk/go/timeseries"
	"github.com/vechain/thorflux/dashgen"
)

// DposFinalityDashboard implements Dashboard interface for the DPoS finality dashboard
type DposFinalityDashboard struct {
	InfluxDBRef    dashboard.DataSourceRef
	DefaultGrafana dashboard.DataSourceRef
}

func (d DposFinalityDashboard) Name() string {
	return "DPoS Finality"
}

func (d DposFinalityDashboard) OutputFilename() string {
	return "dpos-finality.json"
}

func (d DposFinalityDashboard) Generate() (*dashboard.Dashboard, error) {
	// Create the DPoS finality dashboard with bucket templating
	builder := dashboard.NewDashboardBuilder("DPoS Finality Generated").
		Uid("dpos-finality-generated").
		Tags([]string{"generated", "vechain", "thorflux", "dpos", "finality"}).
		Description("DPoS blockchain finality and consensus monitoring - Generated by thorflux dashgen").
		Refresh("30s").
		Time("now-6h", "now").
		Timezone(common.TimeZoneBrowser).
		WithVariable(CreateBucketVariable(*d.InfluxDBRef.Uid)).
		WithPanel(
			// Header panel
			dashgen.StandardHeaderPanel("DPoS Finality", d.DefaultGrafana),
		).
		WithPanel(
			// Finalized block stat panel
			d.finalizedBlockPanel(),
		).
		WithPanel(
			// Justified block stat panel
			d.justifiedBlockPanel(),
		).
		WithPanel(
			// Finality timeline panel
			d.finalityTimelinePanel(),
		).
		WithPanel(
			// Consensus health panel
			d.consensusHealthPanel(),
		).
		WithPanel(
			// Block confirmation time panel
			d.blockConfirmationTimePanel(),
		)

	// Build the dashboard
	dashboardResource, err := builder.Build()
	if err != nil {
		return nil, err
	}

	return &dashboardResource, nil
}

func (d DposFinalityDashboard) finalizedBlockPanel() cog.Builder[dashboard.Panel] {
	return stat.NewPanelBuilder().
		Title("Latest Finalized Block").
		Datasource(d.InfluxDBRef).
		Description("Most recent finalized block number").
		ReduceOptions(common.NewReduceDataOptionsBuilder().
			Calcs([]string{"lastNotNull"}).
			Fields("/.*/")).
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "liveness" and r["_field"] == "finalized")
  |> group()
  |> last()
  |> yield(name: "_value")`, d.InfluxDBRef),
		)
}

func (d DposFinalityDashboard) justifiedBlockPanel() cog.Builder[dashboard.Panel] {
	return stat.NewPanelBuilder().
		Title("Latest Justified Block").
		Datasource(d.InfluxDBRef).
		Description("Most recent justified block number").
		ReduceOptions(common.NewReduceDataOptionsBuilder().
			Calcs([]string{"lastNotNull"}).
			Fields("/.*/")).
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "liveness" and r["_field"] == "justified_block")
  |> group()
  |> last()
  |> yield(name: "_value")`, d.InfluxDBRef),
		)
}

func (d DposFinalityDashboard) finalityTimelinePanel() cog.Builder[dashboard.Panel] {
	return timeseries.NewPanelBuilder().
		Title("Finality Timeline").
		Description("Timeline showing finalized and justified block progression").
		Datasource(d.InfluxDBRef).
		Unit("short").
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "liveness")
  |> filter(fn: (r) => r["_field"] == "finalized" or r["_field"] == "justified_block" or r["_field"] == "current_block")
  |> group(columns: ["_field"])
  |> keep(columns: ["_time", "_value", "_field"])`, d.InfluxDBRef),
		)
}

func (d DposFinalityDashboard) consensusHealthPanel() cog.Builder[dashboard.Panel] {
	return timeseries.NewPanelBuilder().
		Title("Consensus Health").
		Description("Overall health and liveness of the consensus mechanism").
		Datasource(d.InfluxDBRef).
		Unit("percent").
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "liveness" and r["_field"] == "liveness")
  |> group()
  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)
  |> map(fn: (r) => ({ _value: r._value * 100.0, _time: r._time }))`, d.InfluxDBRef),
		)
}

func (d DposFinalityDashboard) blockConfirmationTimePanel() cog.Builder[dashboard.Panel] {
	return timeseries.NewPanelBuilder().
		Title("Block Confirmation Time").
		Description("Time between block creation and finalization").
		Datasource(d.InfluxDBRef).
		Unit("s").
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "block_stats")
  |> filter(fn: (r) => r["_field"] == "best_block_number" or r["_field"] == "finalized_block_number")
  |> group(columns: ["_field"])
  |> aggregateWindow(every: 1m, fn: last, createEmpty: false)`, d.InfluxDBRef),
		)
}
