package dashboards

import (
	"github.com/grafana/grafana-foundation-sdk/go/cog"
	"github.com/grafana/grafana-foundation-sdk/go/common"
	"github.com/grafana/grafana-foundation-sdk/go/dashboard"
	"github.com/grafana/grafana-foundation-sdk/go/stat"
	"github.com/grafana/grafana-foundation-sdk/go/table"
	"github.com/grafana/grafana-foundation-sdk/go/timeseries"
	"github.com/vechain/thorflux/dashgen"
)

// DposContractEventsDashboard implements Dashboard interface for the DPoS contract events dashboard
type DposContractEventsDashboard struct {
	InfluxDBRef    dashboard.DataSourceRef
	DefaultGrafana dashboard.DataSourceRef
}

func (d DposContractEventsDashboard) Name() string {
	return "DPoS Contract Events"
}

func (d DposContractEventsDashboard) OutputFilename() string {
	return "dpos-contract-events.json"
}

func (d DposContractEventsDashboard) Generate() (*dashboard.Dashboard, error) {
	// Create the DPoS contract events dashboard with bucket templating
	builder := dashboard.NewDashboardBuilder("DPoS Contract Events Generated").
		Uid("dpos-contract-events-generated").
		Tags([]string{"generated", "vechain", "thorflux", "dpos", "events", "contracts"}).
		Description("DPoS smart contract events and transactions monitoring - Generated by thorflux dashgen").
		Refresh("30s").
		Time("now-24h", "now").
		Timezone(common.TimeZoneBrowser).
		WithVariable(CreateBucketVariable(*d.InfluxDBRef.Uid)).
		WithPanel(
			// Header panel
			dashgen.StandardHeaderPanel("DPoS Contract Events", d.DefaultGrafana),
		).
		WithPanel(
			// Total events stat panel
			d.totalEventsPanel(dashboard.GridPos{H: PanelHeight, W: HalfWidth, X: 0, Y: HeaderHeight}),
		).
		WithPanel(
			// Event types breakdown panel
			d.eventTypesPanel(dashboard.GridPos{H: PanelHeight, W: HalfWidth, X: HalfWidth, Y: HeaderHeight}),
		).
		WithPanel(
			// Events timeline panel
			d.eventsTimelinePanel(dashboard.GridPos{H: PanelHeight, W: HalfWidth, X: 0, Y: HeaderHeight + PanelHeight}),
		).
		WithPanel(
			// Transaction volume panel
			d.transactionVolumePanel(dashboard.GridPos{H: PanelHeight, W: HalfWidth, X: HalfWidth, Y: HeaderHeight + PanelHeight}),
		).
		WithPanel(
			// Contract interactions table panel
			d.contractInteractionsPanel(dashboard.GridPos{H: PanelHeight, W: FullWidth, X: 0, Y: HeaderHeight + 2*PanelHeight}),
		)

	// Build the dashboard
	dashboardResource, err := builder.Build()
	if err != nil {
		return nil, err
	}

	return &dashboardResource, nil
}

func (d DposContractEventsDashboard) totalEventsPanel(pos dashboard.GridPos) cog.Builder[dashboard.Panel] {
	return stat.NewPanelBuilder().
		Title("Total Contract Events").
		GridPos(pos).
		Datasource(d.InfluxDBRef).
		Description("Total count of DPoS contract events in the selected time range").
		ReduceOptions(common.NewReduceDataOptionsBuilder().
			Calcs([]string{"lastNotNull"}).
			Fields("/.*/")).
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "contract_events")
  |> group()
  |> count()
  |> yield(name: "_value")`, d.InfluxDBRef),
		)
}

func (d DposContractEventsDashboard) eventsTimelinePanel(pos dashboard.GridPos) cog.Builder[dashboard.Panel] {
	return timeseries.NewPanelBuilder().
		Title("Contract Events Timeline").
		GridPos(pos).
		Description("Timeline showing DPoS contract events over time").
		Datasource(d.InfluxDBRef).
		Unit("short").
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "contract_events")
  |> group(columns: ["event_type"])
  |> aggregateWindow(every: 5m, fn: count, createEmpty: false)`, d.InfluxDBRef),
		)
}

func (d DposContractEventsDashboard) contractInteractionsPanel(pos dashboard.GridPos) cog.Builder[dashboard.Panel] {
	return table.NewPanelBuilder().
		Title("Recent Contract Interactions").
		GridPos(pos).
		Datasource(d.InfluxDBRef).
		Description("Table showing recent DPoS contract interactions and events").
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "contract_events")
  |> keep(columns: ["_time", "_value", "event_type", "contract_address", "tx_hash"])
  |> sort(columns: ["_time"], desc: true)
  |> limit(n: 100)`, d.InfluxDBRef),
		)
}

func (d DposContractEventsDashboard) eventTypesPanel(pos dashboard.GridPos) cog.Builder[dashboard.Panel] {
	return stat.NewPanelBuilder().
		Title("Event Types Breakdown").
		GridPos(pos).
		Datasource(d.InfluxDBRef).
		Description("Breakdown of different types of contract events").
		ReduceOptions(common.NewReduceDataOptionsBuilder().
			Calcs([]string{"lastNotNull"}).
			Fields("/.*/")).
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "contract_events")
  |> group(columns: ["event_type"])
  |> count()
  |> group()
  |> sort(columns: ["_value"], desc: true)`, d.InfluxDBRef),
		)
}

func (d DposContractEventsDashboard) transactionVolumePanel(pos dashboard.GridPos) cog.Builder[dashboard.Panel] {
	return timeseries.NewPanelBuilder().
		Title("Transaction Volume").
		GridPos(pos).
		Description("Volume of transactions interacting with DPoS contracts").
		Datasource(d.InfluxDBRef).
		Unit("short").
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "block_stats")
  |> filter(fn: (r) => r["_field"] == "transaction_count")
  |> aggregateWindow(every: 10m, fn: sum, createEmpty: false)`, d.InfluxDBRef),
		)
}
