package dashboards

import (
	"github.com/grafana/grafana-foundation-sdk/go/cog"
	"github.com/grafana/grafana-foundation-sdk/go/common"
	"github.com/grafana/grafana-foundation-sdk/go/dashboard"
	"github.com/grafana/grafana-foundation-sdk/go/timeseries"
	"github.com/vechain/thorflux/dashgen"
)

// DposVthoDashboard implements Dashboard interface for the DPoS VTHO dashboard
type DposVthoDashboard struct {
	InfluxDBRef    dashboard.DataSourceRef
	DefaultGrafana dashboard.DataSourceRef
}

func (d DposVthoDashboard) Name() string {
	return "DPoS VTHO dashboard"
}

func (d DposVthoDashboard) OutputFilename() string {
	return "dpos-vtho-dashboards.json"
}

func (d DposVthoDashboard) Generate() (*dashboard.Dashboard, error) {
	// Create the DPoS VTHO dashboard with bucket templating
	builder := dashboard.NewDashboardBuilder("DPoS VTHO Dashboard Generated").
		Uid("dpos-vtho-dashboards-generated").
		Tags([]string{"generated", "vechain", "thorflux", "dpos", "vtho"}).
		Description("DPoS VTHO issuance and burning analysis dashboard - Generated by thorflux dashgen").
		Refresh("30s").
		Time("now-6h", "now").
		Timezone(common.TimeZoneBrowser).
		WithVariable(CreateBucketVariable(*d.InfluxDBRef.Uid)).
		WithPanel(
			// Header panel
			dashgen.StandardHeaderPanel("DPoS VTHO Dashboard", d.DefaultGrafana),
		).
		WithPanel(
			// Finalized / Justified / Liveness panel
			d.finalizedJustifiedLivenessPanel(),
		).
		WithPanel(
			// Tips panel
			d.tipsPanel(),
		).
		WithPanel(
			// VTHO issued/burned ratio panel
			d.vthoIssuedBurnedRatioPanel(),
		).
		WithPanel(
			// Issued and burned VTHO panel
			d.issuedBurnedVthoPanel(),
		)

	// Build the dashboard
	dashboardResource, err := builder.Build()
	if err != nil {
		return nil, err
	}

	return &dashboardResource, nil
}

func (d DposVthoDashboard) finalizedJustifiedLivenessPanel() cog.Builder[dashboard.Panel] {
	return timeseries.NewPanelBuilder().
		Title("Finalized / Justified / Liveness").
		Description("Time series showing finalized, justified, and liveness metrics").
		Datasource(d.InfluxDBRef).
		Unit("short").
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "liveness" and (r["_field"] == "finalized" or r["_field"] == "justified_block" or r["_field"] == "liveness" or r["_field"] == "current_block"))
  |> drop(columns: ["chain_tag", "block_number", "signer"])`, d.InfluxDBRef),
		)
}

func (d DposVthoDashboard) tipsPanel() cog.Builder[dashboard.Panel] {
	return timeseries.NewPanelBuilder().
		Title("Tips").
		Description("Block tips over time").
		Datasource(d.InfluxDBRef).
		Unit("short").
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "block_stats" and r["_field"] == "block_total_total_tip")
  |> map(fn: (r) => ({ tip: float(v: r._value), time: r._time}))
  |> drop(columns: ["chain_tag", "block_number"])`, d.InfluxDBRef),
		)
}

func (d DposVthoDashboard) vthoIssuedBurnedRatioPanel() cog.Builder[dashboard.Panel] {
	return timeseries.NewPanelBuilder().
		Title("VTHO - issued / burned (Finney)").
		Description("VTHO issued to burned ratio in Finney units").
		Datasource(d.InfluxDBRef).
		Unit("short").
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "hayabusa_gas")
  |> filter(fn: (r) => r["_field"] == "issued_burned_ratio")
  |> drop(columns: ["chain_tag"])`, d.InfluxDBRef),
		)
}

func (d DposVthoDashboard) issuedBurnedVthoPanel() cog.Builder[dashboard.Panel] {
	return timeseries.NewPanelBuilder().
		Title("Issued and burned VTHO (Finney)").
		Description("VTHO issuance and burning with validator and delegator shares").
		Datasource(d.InfluxDBRef).
		Unit("short").
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "hayabusa_gas")
  |> filter(fn: (r) => r["_field"] == "vtho_burned" or r["_field"] == "vtho_issued" or r["_field"] == "validators_share" or r["_field"] == "delegators_share")
  |> drop(columns: ["chain_tag"])`, d.InfluxDBRef),
		)
}
