package dashboards

import (
	"github.com/grafana/grafana-foundation-sdk/go/cog"
	"github.com/grafana/grafana-foundation-sdk/go/common"
	"github.com/grafana/grafana-foundation-sdk/go/dashboard"
	"github.com/grafana/grafana-foundation-sdk/go/stat"
	"github.com/grafana/grafana-foundation-sdk/go/timeseries"
	"github.com/vechain/thorflux/dashgen"
)

// NetworkOverviewDashboard implements DashboardGenerator for the network overview dashboard
type NetworkOverviewDashboard struct {
	InfluxDBRef    dashboard.DataSourceRef
	DefaultGrafana dashboard.DataSourceRef
}

func (d NetworkOverviewDashboard) Name() string {
	return "Network Overview"
}

func (d NetworkOverviewDashboard) OutputFilename() string {
	return "network-overview.json"
}

func (d NetworkOverviewDashboard) Generate() (*dashboard.Dashboard, error) {
	// Create the main dashboard builder with bucket templating
	builder := dashboard.NewDashboardBuilder("Network Overview Generated").
		Uid("network-overview-generated").
		Tags([]string{"generated", "vechain", "thorflux"}).
		Description("The ability to quickly look at the network stats and get an impression of how the chain is progressing - Generated by thorflux dashgen").
		Refresh("5m").
		Time("now-1h", "now").
		Timezone(common.TimeZoneBrowser).
		WithVariable(CreateBucketVariable(*d.InfluxDBRef.Uid)).
		WithPanel(
			// Header panel
			dashgen.StandardHeaderPanel("Network Overview", d.DefaultGrafana),
		).
		WithPanel(
			// Missed slots stat panel
			d.missedSlotsStatsPanel(dashboard.GridPos{X: 0, Y: HeaderHeight, W: HalfWidth, H: PanelHeight}),
		).
		WithPanel(
			// Block height time series panel
			d.blockHeightPanel(dashboard.GridPos{X: HalfWidth, Y: HeaderHeight, W: HalfWidth, H: PanelHeight}),
		)

	// Build the dashboard
	dashboardResource, err := builder.Build()
	if err != nil {
		return nil, err
	}

	return &dashboardResource, nil
}

func (d NetworkOverviewDashboard) missedSlotsStatsPanel(pos dashboard.GridPos) cog.Builder[dashboard.Panel] {
	return stat.NewPanelBuilder().
		Title("Missed Slots").
		GridPos(pos).
		Datasource(d.InfluxDBRef).
		Description("Number of missed validator slots").
		ReduceOptions(common.NewReduceDataOptionsBuilder().
			Calcs([]string{"lastNotNull"}).
			Fields("/.*/")).
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r["_measurement"] == "recent_slots" and r["_field"] == "block_number") |> filter(fn: (r) => r.filled == "0") |> group() |> count() |> yield(name: "_value")`, d.InfluxDBRef),
		)
}

func (d NetworkOverviewDashboard) blockHeightPanel(pos dashboard.GridPos) cog.Builder[dashboard.Panel] {
	return timeseries.NewPanelBuilder().
		Title("Block Height").
		GridPos(pos).
		Description("Current block height of the VeChain network").
		Datasource(d.InfluxDBRef).
		Unit("short").
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r["_measurement"] == "block_stats") |> filter(fn: (r) => r["_field"] == "best_block_number") |> group(columns: ["best_block_number"]) |> last()`, d.InfluxDBRef),
		)
}
