package dashboards

import (
	"github.com/grafana/grafana-foundation-sdk/go/cog"
	"github.com/grafana/grafana-foundation-sdk/go/common"
	"github.com/grafana/grafana-foundation-sdk/go/dashboard"
	"github.com/grafana/grafana-foundation-sdk/go/stat"
	"github.com/grafana/grafana-foundation-sdk/go/table"
	"github.com/vechain/thorflux/dashgen"
)

// SingleAuthViewDashboard implements Dashboard interface for the single authority view dashboard
type SingleAuthViewDashboard struct {
	InfluxDBRef    dashboard.DataSourceRef
	DefaultGrafana dashboard.DataSourceRef
}

func (d SingleAuthViewDashboard) Name() string {
	return "Single Authority View"
}

func (d SingleAuthViewDashboard) OutputFilename() string {
	return "single-auth-view.json"
}

func (d SingleAuthViewDashboard) Generate() (*dashboard.Dashboard, error) {
	// Create the single authority view dashboard with templating
	builder := dashboard.NewDashboardBuilder("Single Authority View Generated").
		Uid("single-auth-view-generated").
		Tags([]string{"generated", "vechain", "thorflux", "authority", "single"}).
		Description("Detailed view of a single VeChain Thor authority node performance - Generated by thorflux dashgen").
		Refresh("30s").
		Time("now-6h", "now").
		Timezone(common.TimeZoneBrowser).
		WithVariable(CreateBucketVariable(*d.InfluxDBRef.Uid)).
		WithVariable(d.createProposerVariable()).
		WithPanel(
			// Header panel
			dashgen.StandardHeaderPanel("Single Authority View", d.DefaultGrafana),
		).
		WithPanel(
			// Missed slots stat panel
			d.missedSlotsStatPanel(dashboard.GridPos{H: PanelHeight, W: ThirdWidth, X: 0, Y: HeaderHeight}),
		).
		WithPanel(
			// Filled slots stat panel
			d.filledSlotsStatPanel(dashboard.GridPos{H: PanelHeight, W: ThirdWidth, X: ThirdWidth, Y: HeaderHeight}),
		).
		WithPanel(
			// Missed/Filled slots percentage panel
			d.missedFilledPercentagePanel(dashboard.GridPos{H: PanelHeight, W: ThirdWidth, X: 2*ThirdWidth, Y: HeaderHeight}),
		).
		WithPanel(
			// Filled slots table panel
			d.filledSlotsTablePanel(dashboard.GridPos{H: PanelHeight, W: HalfWidth, X: 0, Y: HeaderHeight + PanelHeight}),
		).
		WithPanel(
			// Missed slots table panel
			d.missedSlotsTablePanel(dashboard.GridPos{H: PanelHeight, W: HalfWidth, X: HalfWidth, Y: HeaderHeight + PanelHeight}),
		)

	// Build the dashboard
	dashboardResource, err := builder.Build()
	if err != nil {
		return nil, err
	}

	return &dashboardResource, nil
}

func (d SingleAuthViewDashboard) createProposerVariable() *dashboard.QueryVariableBuilder {
	// Create StringOrMap for proposer query
	query := dashboard.StringOrMap{
		String: cog.ToPtr(`import "influxdata/influxdb/schema"

schema.tagValues(bucket: "${bucket}", tag: "proposer")`),
	}

	// Create VariableOption for current value
	current := dashboard.VariableOption{
		Selected: cog.ToPtr(false),
		Text: dashboard.StringOrArrayOfString{
			String: cog.ToPtr(""),
		},
		Value: dashboard.StringOrArrayOfString{
			String: cog.ToPtr(""),
		},
	}

	return dashboard.NewQueryVariableBuilder("proposer").
		Datasource(dashboard.DataSourceRef{
			Type: cog.ToPtr("influxdb"),
			Uid:  cog.ToPtr(*d.InfluxDBRef.Uid),
		}).
		Query(query).
		Label("Proposer").
		Current(current).
		Hide(dashboard.VariableHideDontHide).
		Multi(false).
		Refresh(dashboard.VariableRefreshOnTimeRangeChanged)
}

func (d SingleAuthViewDashboard) filledSlotsTablePanel(pos dashboard.GridPos) cog.Builder[dashboard.Panel] {
	return table.NewPanelBuilder().
		Title("Filled Slots").
		GridPos(pos).
		Datasource(d.InfluxDBRef).
		Description("Table showing filled slots for the selected proposer").
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "recent_slots" and r["_field"] == "block_number" and r.filled == "1" and r.proposer == "${proposer}")
  |> limit(n: 1000)
  |> map(fn: (r) => ({ slot: r._value, time: r._time}))
  |> keep(columns: ["slot", "time"])`, d.InfluxDBRef),
		)
}

func (d SingleAuthViewDashboard) missedSlotsStatPanel(pos dashboard.GridPos) cog.Builder[dashboard.Panel] {
	return stat.NewPanelBuilder().
		Title("Missed Slots").
		GridPos(pos).
		Datasource(d.InfluxDBRef).
		Description("Total count of missed slots for the selected proposer").
		ReduceOptions(common.NewReduceDataOptionsBuilder().
			Calcs([]string{"lastNotNull"}).
			Fields("/.*/")).
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "recent_slots")
  |> filter(fn: (r) => r["_field"] == "block_number")
  |> filter(fn: (r) => r["proposer"] == "${proposer}")
  |> filter(fn: (r) => r["filled"] == "0")
  |> group()
  |> count()
  |> yield(name: "_value")`, d.InfluxDBRef),
		)
}

func (d SingleAuthViewDashboard) filledSlotsStatPanel(pos dashboard.GridPos) cog.Builder[dashboard.Panel] {
	return stat.NewPanelBuilder().
		Title("Filled Slots").
		GridPos(pos).
		Datasource(d.InfluxDBRef).
		Description("Total count of filled slots for the selected proposer").
		ReduceOptions(common.NewReduceDataOptionsBuilder().
			Calcs([]string{"lastNotNull"}).
			Fields("/.*/")).
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "recent_slots")
  |> filter(fn: (r) => r["_field"] == "block_number")
  |> filter(fn: (r) => r["proposer"] == "${proposer}")
  |> filter(fn: (r) => r["filled"] == "1")
  |> group()
  |> count()
  |> yield(name: "_value")`, d.InfluxDBRef),
		)
}

func (d SingleAuthViewDashboard) missedSlotsTablePanel(pos dashboard.GridPos) cog.Builder[dashboard.Panel] {
	return table.NewPanelBuilder().
		Title("Missed Slots").
		GridPos(pos).
		Datasource(d.InfluxDBRef).
		Description("Table showing missed slots for the selected proposer").
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "recent_slots" and r["_field"] == "block_number" and r.filled == "0" and r.proposer == "${proposer}")
  |> map(fn: (r) => ({ slot: r._value, time: r._time}))
  |> keep(columns: ["slot", "time"])`, d.InfluxDBRef),
		)
}

func (d SingleAuthViewDashboard) missedFilledPercentagePanel(pos dashboard.GridPos) cog.Builder[dashboard.Panel] {
	return stat.NewPanelBuilder().
		Title("Missed/Filled slots %").
		GridPos(pos).
		Datasource(d.InfluxDBRef).
		Description("Percentage of missed slots vs filled slots for the selected proposer").
		Unit("percent").
		ReduceOptions(common.NewReduceDataOptionsBuilder().
			Calcs([]string{"lastNotNull"}).
			Fields("/.*/")).
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `a = from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "recent_slots")
  |> filter(fn: (r) => r["_field"] == "block_number")
  |> filter(fn: (r) => r["proposer"] == "${proposer}")
  |> filter(fn: (r) => r["filled"] == "0")
  |> group()
  |> count()
      |> map(
        fn: (r) => ({
            _join: 0,
            _value_a: r._value
        }),
    )

b = from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "recent_slots")
  |> filter(fn: (r) => r["_field"] == "block_number")
  |> filter(fn: (r) => r["proposer"] == "${proposer}")
  |> filter(fn: (r) => r["filled"] == "1")
  |> group()
  |> count()
      |> map(
        fn: (r) => ({
            _join: 0,
            _value_b: r._value
        }),
    )

join(tables: {a: a, b: b}, on: ["_join"])
  |> drop(columns: ["_join"])
  |> map(
        fn: (r) => ({
            _value: float(v: r._value_a) / float(v: r._value_b) * 100.0
        }),
    )`, d.InfluxDBRef),
		)
}
