package dashboards

import (
	"github.com/grafana/grafana-foundation-sdk/go/cog"
	"github.com/grafana/grafana-foundation-sdk/go/common"
	"github.com/grafana/grafana-foundation-sdk/go/dashboard"
	"github.com/grafana/grafana-foundation-sdk/go/stat"
	"github.com/grafana/grafana-foundation-sdk/go/timeseries"
	"github.com/vechain/thorflux/dashgen"
)

// ValidatorsDashboard implements Dashboard interface for the validators overview dashboard
type ValidatorsDashboard struct {
	InfluxDBRef    dashboard.DataSourceRef
	DefaultGrafana dashboard.DataSourceRef
}

func (d ValidatorsDashboard) Name() string {
	return "Validators Overview"
}

func (d ValidatorsDashboard) OutputFilename() string {
	return "validators-overview.json"
}

func (d ValidatorsDashboard) Generate() (*dashboard.Dashboard, error) {

	// Create the validators dashboard with bucket templating
	builder := dashboard.NewDashboardBuilder("Validators Overview Generated").
		Uid("validators-overview-generated").
		Tags([]string{"generated", "vechain", "thorflux", "validators"}).
		Description("Overview of VeChain Thor validator performance and metrics - Generated by thorflux dashgen").
		Refresh("30s").
		Time("now-24h", "now").
		Timezone(common.TimeZoneBrowser).
		WithVariable(CreateBucketVariable(*d.InfluxDBRef.Uid)).
		WithPanel(
			// Header panel
			dashgen.StandardHeaderPanel("Validators Overview", d.DefaultGrafana),
		).
		WithPanel(
			// Active validators count
			d.activeValidatorsPanel(dashboard.GridPos{H: PanelHeight, W: HalfWidth, X: 0, Y: HeaderHeight}),
		).
		WithPanel(
			// Validator performance over time
			d.validatorPerformancePanel(dashboard.GridPos{H: PanelHeight, W: HalfWidth, X: HalfWidth, Y: HeaderHeight}),
		)

	// Build the dashboard
	dashboardResource, err := builder.Build()
	if err != nil {
		return nil, err
	}

	return &dashboardResource, nil
}

func (d ValidatorsDashboard) activeValidatorsPanel(pos dashboard.GridPos) cog.Builder[dashboard.Panel] {
	return stat.NewPanelBuilder().
		Title("Active Validators").
		GridPos(pos).
		Datasource(d.InfluxDBRef).
		Description("Total number of active validators").
		ReduceOptions(common.NewReduceDataOptionsBuilder().
			Calcs([]string{"lastNotNull"}).
			Fields("/.*/")).
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r["_field"] == "block_signer" ) |> filter(fn: (r) => r["_measurement"] == "block_stats" ) |> keep(columns: ["signer"]) |> group() |> distinct(column: "signer") |> count()`, d.InfluxDBRef),
		)
}

func (d ValidatorsDashboard) validatorPerformancePanel(pos dashboard.GridPos) cog.Builder[dashboard.Panel] {
	return timeseries.NewPanelBuilder().
		Title("Validator Performance").
		GridPos(pos).
		Description("Performance metrics of validators over time").
		Datasource(d.InfluxDBRef).
		Unit("percent").
		WithTarget(
			dashgen.NewInfluxDBQuery("A", `from(bucket: "${bucket}") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r["_measurement"] == "liveness") |> filter(fn: (r) => r["_field"] == "liveness") |> group(columns: ["_field"]) |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) |> yield(name: "mean")`, d.InfluxDBRef),
		)
}
