{
 "title": "Authority Overview",
 "time": { "from": "now-15d", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "label": "Bucket", "query": "buckets()" }
  ]
 },
 "panels": [
  {
   "title": "# of Signers",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"block_stats\" \n  )\n  |> keep(columns: [\"signer\"])\n  |> group()\n  |> distinct(column: \"signer\")\n  |> count()"
    }
   ]
  },
  {
   "title": "Missed Slots (Ignore 'block_number')",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "query": "import \"strings\"\n\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"recent_slots\" and r[\"_field\"] == \"block_number\" and r[\"filled\"] == \"0\")\n  |> map(fn: (r) => ({ r with _value: 1 })) \n  |> drop(columns: [\"chain_tag\", \"filled\"])\n"
    }
   ]
  },
  {
   "title": "Total Missed Solts",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"recent_slots\" and r[\"_field\"] == \"block_number\")\n  |> filter(fn: (r) => r.filled == \"0\")\n |> filter(fn: (r) => r[\"chain_tag\"] != \"\")\n |> group()\n  |> unique(column: \"_value\")\n |> count()\n  |> yield(name: \"_value\")"
    }
   ]
  },
  {
   "title": "Worst Performing (Click Address to View Single Authority)",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"recent_slots\")\n  |> filter(fn: (r) => r[\"filled\"] == \"0\")\n |> filter(fn: (r) => r[\"chain_tag\"] != \"\")\n |> group(columns: [\"proposer\",\"owner\",\"contact\"])\n  |> count(column: \"_value\")\n  |> group()\n  |> sort(columns: [\"_value\"], desc: true)\n  |> map(fn: (r) => ({ r with count: r._value / 2})) \n  |> keep(columns: [\"count\", \"proposer\",\"owner\",\"contact\"])"
    }
   ]
  },
  {
   "title": "Most Proposed Blocks",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"recent_slots\")\n  |> filter(fn: (r) => r[\"filled\"] == \"1\")\n  |> group(columns: [\"proposer\", \"owner\",\"contact\"])\n  |> count(column: \"_value\")\n  |> group()\n  |> sort(columns: [\"_value\"], desc: true)\n  |> map(fn: (r) => ({ r with count: r._value / 2})) \n  |> keep(columns: [\"count\", \"proposer\", \"owner\",\"contact\"])"
    }
   ]
  }
 ]
}